FROM --platform=$BUILDPLATFORM golang:1.20@sha256:690e4135bf2a4571a572bfd5ddfa806b1cb9c3dea0446ebadaf32bc2ea09d4f9 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.17@sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-matrix"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-matrix"

COPY --from=build /src/dist/drone-matrix /bin/drone-matrix
ENTRYPOINT [ "/bin/drone-matrix" ]
