FROM arm32v7/alpine:3.15@sha256:f27e041ac7ade71ebe7177443bf21d87bbd7a74b9c9f46d0120ffa54cd073ad4

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-matrix"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-matrix"

ADD release/arm/drone-matrix /bin/
ENTRYPOINT [ "/bin/drone-matrix" ]
