FROM alpine:3.16@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-matrix"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-matrix"

ADD dist/drone-matrix /bin/
ENTRYPOINT [ "/bin/drone-matrix" ]
