FROM arm32v7/alpine:3.15@sha256:392d9d85dff31e34d756be33579f05ef493cb1b0edccc36a11b3295365553bfd

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-matrix"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-matrix"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-matrix"

ADD release/arm/drone-matrix /bin/
ENTRYPOINT [ "/bin/drone-matrix" ]
